import './globals.css'

export const metadata = {
  title: 'Rent Moto Cebu',
  description: 'Generated by create next app',
}

export default function Layout ({children}) {
    
 return (
    <html>
    <body>
     
        {children}
        
    </body>
</html>
 )
}