"use client";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Header from "./components/Navbar";
import { Providers } from "./GlobalRedux/provider";
import { ApiProvider } from "@reduxjs/toolkit/dist/query/react";
import { authenticationApi } from "./GlobalRedux/Features/apiServices/AuthenticationAPI";

export const metadata = {
  title: "Rent Moto Cebu",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html>
      <body>
        <Providers>
          <ApiProvider api={authenticationApi}>
            <Header />
            {children}
          </ApiProvider>
        </Providers>
      </body>
    </html>
  );
}
